package test.model;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carId
     *
     * @mbg.generated
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.cartype
     *
     * @mbg.generated
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.routenumber
     *
     * @mbg.generated
     */
    private String routenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.dateproduction
     *
     * @mbg.generated
     */
    private Date dateproduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.purchasedate
     *
     * @mbg.generated
     */
    private Date purchasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carId
     *
     * @return the value of car.carId
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carId
     *
     * @param carid the value for car.carId
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.cartype
     *
     * @return the value of car.cartype
     *
     * @mbg.generated
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.cartype
     *
     * @param cartype the value for car.cartype
     *
     * @mbg.generated
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.routenumber
     *
     * @return the value of car.routenumber
     *
     * @mbg.generated
     */
    public String getRoutenumber() {
        return routenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.routenumber
     *
     * @param routenumber the value for car.routenumber
     *
     * @mbg.generated
     */
    public void setRoutenumber(String routenumber) {
        this.routenumber = routenumber == null ? null : routenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.dateproduction
     *
     * @return the value of car.dateproduction
     *
     * @mbg.generated
     */
    public Date getDateproduction() {
        return dateproduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.dateproduction
     *
     * @param dateproduction the value for car.dateproduction
     *
     * @mbg.generated
     */
    public void setDateproduction(Date dateproduction) {
        this.dateproduction = dateproduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.purchasedate
     *
     * @return the value of car.purchasedate
     *
     * @mbg.generated
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.purchasedate
     *
     * @param purchasedate the value for car.purchasedate
     *
     * @mbg.generated
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.note
     *
     * @return the value of car.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.note
     *
     * @param note the value for car.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}