package test.model;

public class Cityareas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityareas.areasId
     *
     * @mbg.generated
     */
    private String areasid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityareas.areasname
     *
     * @mbg.generated
     */
    private String areasname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityareas.cityId
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityareas.areasId
     *
     * @return the value of cityareas.areasId
     *
     * @mbg.generated
     */
    public String getAreasid() {
        return areasid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityareas.areasId
     *
     * @param areasid the value for cityareas.areasId
     *
     * @mbg.generated
     */
    public void setAreasid(String areasid) {
        this.areasid = areasid == null ? null : areasid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityareas.areasname
     *
     * @return the value of cityareas.areasname
     *
     * @mbg.generated
     */
    public String getAreasname() {
        return areasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityareas.areasname
     *
     * @param areasname the value for cityareas.areasname
     *
     * @mbg.generated
     */
    public void setAreasname(String areasname) {
        this.areasname = areasname == null ? null : areasname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityareas.cityId
     *
     * @return the value of cityareas.cityId
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityareas.cityId
     *
     * @param cityid the value for cityareas.cityId
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }
}