package test.model;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityId
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityname
     *
     * @mbg.generated
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.provincesId
     *
     * @mbg.generated
     */
    private String provincesid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityId
     *
     * @return the value of city.cityId
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityId
     *
     * @param cityid the value for city.cityId
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityname
     *
     * @return the value of city.cityname
     *
     * @mbg.generated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityname
     *
     * @param cityname the value for city.cityname
     *
     * @mbg.generated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.provincesId
     *
     * @return the value of city.provincesId
     *
     * @mbg.generated
     */
    public String getProvincesid() {
        return provincesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.provincesId
     *
     * @param provincesid the value for city.provincesId
     *
     * @mbg.generated
     */
    public void setProvincesid(String provincesid) {
        this.provincesid = provincesid == null ? null : provincesid.trim();
    }
}