package test.model;

public class Orderfrom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.orderId
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.commodityname
     *
     * @mbg.generated
     */
    private String commodityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.commodityweight
     *
     * @mbg.generated
     */
    private Integer commodityweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.sender
     *
     * @mbg.generated
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.mailingaddress
     *
     * @mbg.generated
     */
    private String mailingaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.shippingaddress
     *
     * @mbg.generated
     */
    private String shippingaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.postphone
     *
     * @mbg.generated
     */
    private String postphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.consigneenumber
     *
     * @mbg.generated
     */
    private String consigneenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.startingcity
     *
     * @mbg.generated
     */
    private String startingcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.middlecity
     *
     * @mbg.generated
     */
    private String middlecity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.terminationcity
     *
     * @mbg.generated
     */
    private String terminationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.transportprice
     *
     * @mbg.generated
     */
    private Long transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.shippingprice
     *
     * @mbg.generated
     */
    private Long shippingprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.yunshuprice
     *
     * @mbg.generated
     */
    private Long yunshuprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.vehicle
     *
     * @mbg.generated
     */
    private String vehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderfrom.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.orderId
     *
     * @return the value of orderfrom.orderId
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.orderId
     *
     * @param orderid the value for orderfrom.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.order_type
     *
     * @return the value of orderfrom.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.order_type
     *
     * @param orderType the value for orderfrom.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.order_number
     *
     * @return the value of orderfrom.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.order_number
     *
     * @param orderNumber the value for orderfrom.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.commodityname
     *
     * @return the value of orderfrom.commodityname
     *
     * @mbg.generated
     */
    public String getCommodityname() {
        return commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.commodityname
     *
     * @param commodityname the value for orderfrom.commodityname
     *
     * @mbg.generated
     */
    public void setCommodityname(String commodityname) {
        this.commodityname = commodityname == null ? null : commodityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.commodityweight
     *
     * @return the value of orderfrom.commodityweight
     *
     * @mbg.generated
     */
    public Integer getCommodityweight() {
        return commodityweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.commodityweight
     *
     * @param commodityweight the value for orderfrom.commodityweight
     *
     * @mbg.generated
     */
    public void setCommodityweight(Integer commodityweight) {
        this.commodityweight = commodityweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.sender
     *
     * @return the value of orderfrom.sender
     *
     * @mbg.generated
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.sender
     *
     * @param sender the value for orderfrom.sender
     *
     * @mbg.generated
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.mailingaddress
     *
     * @return the value of orderfrom.mailingaddress
     *
     * @mbg.generated
     */
    public String getMailingaddress() {
        return mailingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.mailingaddress
     *
     * @param mailingaddress the value for orderfrom.mailingaddress
     *
     * @mbg.generated
     */
    public void setMailingaddress(String mailingaddress) {
        this.mailingaddress = mailingaddress == null ? null : mailingaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.shippingaddress
     *
     * @return the value of orderfrom.shippingaddress
     *
     * @mbg.generated
     */
    public String getShippingaddress() {
        return shippingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.shippingaddress
     *
     * @param shippingaddress the value for orderfrom.shippingaddress
     *
     * @mbg.generated
     */
    public void setShippingaddress(String shippingaddress) {
        this.shippingaddress = shippingaddress == null ? null : shippingaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.state
     *
     * @return the value of orderfrom.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.state
     *
     * @param state the value for orderfrom.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.postphone
     *
     * @return the value of orderfrom.postphone
     *
     * @mbg.generated
     */
    public String getPostphone() {
        return postphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.postphone
     *
     * @param postphone the value for orderfrom.postphone
     *
     * @mbg.generated
     */
    public void setPostphone(String postphone) {
        this.postphone = postphone == null ? null : postphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.consignee
     *
     * @return the value of orderfrom.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.consignee
     *
     * @param consignee the value for orderfrom.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.consigneenumber
     *
     * @return the value of orderfrom.consigneenumber
     *
     * @mbg.generated
     */
    public String getConsigneenumber() {
        return consigneenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.consigneenumber
     *
     * @param consigneenumber the value for orderfrom.consigneenumber
     *
     * @mbg.generated
     */
    public void setConsigneenumber(String consigneenumber) {
        this.consigneenumber = consigneenumber == null ? null : consigneenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.startingcity
     *
     * @return the value of orderfrom.startingcity
     *
     * @mbg.generated
     */
    public String getStartingcity() {
        return startingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.startingcity
     *
     * @param startingcity the value for orderfrom.startingcity
     *
     * @mbg.generated
     */
    public void setStartingcity(String startingcity) {
        this.startingcity = startingcity == null ? null : startingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.middlecity
     *
     * @return the value of orderfrom.middlecity
     *
     * @mbg.generated
     */
    public String getMiddlecity() {
        return middlecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.middlecity
     *
     * @param middlecity the value for orderfrom.middlecity
     *
     * @mbg.generated
     */
    public void setMiddlecity(String middlecity) {
        this.middlecity = middlecity == null ? null : middlecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.terminationcity
     *
     * @return the value of orderfrom.terminationcity
     *
     * @mbg.generated
     */
    public String getTerminationcity() {
        return terminationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.terminationcity
     *
     * @param terminationcity the value for orderfrom.terminationcity
     *
     * @mbg.generated
     */
    public void setTerminationcity(String terminationcity) {
        this.terminationcity = terminationcity == null ? null : terminationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.transportprice
     *
     * @return the value of orderfrom.transportprice
     *
     * @mbg.generated
     */
    public Long getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.transportprice
     *
     * @param transportprice the value for orderfrom.transportprice
     *
     * @mbg.generated
     */
    public void setTransportprice(Long transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.shippingprice
     *
     * @return the value of orderfrom.shippingprice
     *
     * @mbg.generated
     */
    public Long getShippingprice() {
        return shippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.shippingprice
     *
     * @param shippingprice the value for orderfrom.shippingprice
     *
     * @mbg.generated
     */
    public void setShippingprice(Long shippingprice) {
        this.shippingprice = shippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.yunshuprice
     *
     * @return the value of orderfrom.yunshuprice
     *
     * @mbg.generated
     */
    public Long getYunshuprice() {
        return yunshuprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.yunshuprice
     *
     * @param yunshuprice the value for orderfrom.yunshuprice
     *
     * @mbg.generated
     */
    public void setYunshuprice(Long yunshuprice) {
        this.yunshuprice = yunshuprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.price
     *
     * @return the value of orderfrom.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.price
     *
     * @param price the value for orderfrom.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.vehicle
     *
     * @return the value of orderfrom.vehicle
     *
     * @mbg.generated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.vehicle
     *
     * @param vehicle the value for orderfrom.vehicle
     *
     * @mbg.generated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderfrom.note
     *
     * @return the value of orderfrom.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderfrom.note
     *
     * @param note the value for orderfrom.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}