package test.model;

import java.util.Date;

public class Receipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.startingcity
     *
     * @mbg.generated
     */
    private String startingcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.middlecity
     *
     * @mbg.generated
     */
    private String middlecity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.terminationcity
     *
     * @mbg.generated
     */
    private String terminationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.generatetime
     *
     * @mbg.generated
     */
    private Date generatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.startingcity
     *
     * @return the value of receipt.startingcity
     *
     * @mbg.generated
     */
    public String getStartingcity() {
        return startingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.startingcity
     *
     * @param startingcity the value for receipt.startingcity
     *
     * @mbg.generated
     */
    public void setStartingcity(String startingcity) {
        this.startingcity = startingcity == null ? null : startingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.middlecity
     *
     * @return the value of receipt.middlecity
     *
     * @mbg.generated
     */
    public String getMiddlecity() {
        return middlecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.middlecity
     *
     * @param middlecity the value for receipt.middlecity
     *
     * @mbg.generated
     */
    public void setMiddlecity(String middlecity) {
        this.middlecity = middlecity == null ? null : middlecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.terminationcity
     *
     * @return the value of receipt.terminationcity
     *
     * @mbg.generated
     */
    public String getTerminationcity() {
        return terminationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.terminationcity
     *
     * @param terminationcity the value for receipt.terminationcity
     *
     * @mbg.generated
     */
    public void setTerminationcity(String terminationcity) {
        this.terminationcity = terminationcity == null ? null : terminationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.state
     *
     * @return the value of receipt.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.state
     *
     * @param state the value for receipt.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.generatetime
     *
     * @return the value of receipt.generatetime
     *
     * @mbg.generated
     */
    public Date getGeneratetime() {
        return generatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.generatetime
     *
     * @param generatetime the value for receipt.generatetime
     *
     * @mbg.generated
     */
    public void setGeneratetime(Date generatetime) {
        this.generatetime = generatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.note
     *
     * @return the value of receipt.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.note
     *
     * @param note the value for receipt.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}