package test.model;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routenumber
     *
     * @mbg.generated
     */
    private String routenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routename
     *
     * @mbg.generated
     */
    private String routename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.initialprovince
     *
     * @mbg.generated
     */
    private String initialprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.initialcity
     *
     * @mbg.generated
     */
    private String initialcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midpointprovince
     *
     * @mbg.generated
     */
    private String midpointprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midpointcity
     *
     * @mbg.generated
     */
    private String midpointcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.finalprovince
     *
     * @mbg.generated
     */
    private String finalprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.destinationcity
     *
     * @mbg.generated
     */
    private String destinationcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.transportprice
     *
     * @mbg.generated
     */
    private Long transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routenumber
     *
     * @return the value of route.routenumber
     *
     * @mbg.generated
     */
    public String getRoutenumber() {
        return routenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routenumber
     *
     * @param routenumber the value for route.routenumber
     *
     * @mbg.generated
     */
    public void setRoutenumber(String routenumber) {
        this.routenumber = routenumber == null ? null : routenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routename
     *
     * @return the value of route.routename
     *
     * @mbg.generated
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routename
     *
     * @param routename the value for route.routename
     *
     * @mbg.generated
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.initialprovince
     *
     * @return the value of route.initialprovince
     *
     * @mbg.generated
     */
    public String getInitialprovince() {
        return initialprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.initialprovince
     *
     * @param initialprovince the value for route.initialprovince
     *
     * @mbg.generated
     */
    public void setInitialprovince(String initialprovince) {
        this.initialprovince = initialprovince == null ? null : initialprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.initialcity
     *
     * @return the value of route.initialcity
     *
     * @mbg.generated
     */
    public String getInitialcity() {
        return initialcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.initialcity
     *
     * @param initialcity the value for route.initialcity
     *
     * @mbg.generated
     */
    public void setInitialcity(String initialcity) {
        this.initialcity = initialcity == null ? null : initialcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midpointprovince
     *
     * @return the value of route.midpointprovince
     *
     * @mbg.generated
     */
    public String getMidpointprovince() {
        return midpointprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midpointprovince
     *
     * @param midpointprovince the value for route.midpointprovince
     *
     * @mbg.generated
     */
    public void setMidpointprovince(String midpointprovince) {
        this.midpointprovince = midpointprovince == null ? null : midpointprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midpointcity
     *
     * @return the value of route.midpointcity
     *
     * @mbg.generated
     */
    public String getMidpointcity() {
        return midpointcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midpointcity
     *
     * @param midpointcity the value for route.midpointcity
     *
     * @mbg.generated
     */
    public void setMidpointcity(String midpointcity) {
        this.midpointcity = midpointcity == null ? null : midpointcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.finalprovince
     *
     * @return the value of route.finalprovince
     *
     * @mbg.generated
     */
    public String getFinalprovince() {
        return finalprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.finalprovince
     *
     * @param finalprovince the value for route.finalprovince
     *
     * @mbg.generated
     */
    public void setFinalprovince(String finalprovince) {
        this.finalprovince = finalprovince == null ? null : finalprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.destinationcity
     *
     * @return the value of route.destinationcity
     *
     * @mbg.generated
     */
    public String getDestinationcity() {
        return destinationcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.destinationcity
     *
     * @param destinationcity the value for route.destinationcity
     *
     * @mbg.generated
     */
    public void setDestinationcity(String destinationcity) {
        this.destinationcity = destinationcity == null ? null : destinationcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.transportprice
     *
     * @return the value of route.transportprice
     *
     * @mbg.generated
     */
    public Long getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.transportprice
     *
     * @param transportprice the value for route.transportprice
     *
     * @mbg.generated
     */
    public void setTransportprice(Long transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.note
     *
     * @return the value of route.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.note
     *
     * @param note the value for route.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}