package test.model;

public class Scope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.scopeId
     *
     * @mbg.generated
     */
    private Integer scopeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.areasname
     *
     * @mbg.generated
     */
    private String areasname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.cityId
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.scopeId
     *
     * @return the value of scope.scopeId
     *
     * @mbg.generated
     */
    public Integer getScopeid() {
        return scopeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.scopeId
     *
     * @param scopeid the value for scope.scopeId
     *
     * @mbg.generated
     */
    public void setScopeid(Integer scopeid) {
        this.scopeid = scopeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.areasname
     *
     * @return the value of scope.areasname
     *
     * @mbg.generated
     */
    public String getAreasname() {
        return areasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.areasname
     *
     * @param areasname the value for scope.areasname
     *
     * @mbg.generated
     */
    public void setAreasname(String areasname) {
        this.areasname = areasname == null ? null : areasname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.price
     *
     * @return the value of scope.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.price
     *
     * @param price the value for scope.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.cityId
     *
     * @return the value of scope.cityId
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.cityId
     *
     * @param cityid the value for scope.cityId
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.note
     *
     * @return the value of scope.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.note
     *
     * @param note the value for scope.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}