package test.dao;

import java.util.List;
import test.model.Cityareas;

public interface CityareasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityareas
     *
     * @mbg.generated
     */
    int insert(Cityareas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityareas
     *
     * @mbg.generated
     */
    List<Cityareas> selectAll();
}