package test.dao;

import java.util.List;
import test.model.Distribution;

public interface DistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int insert(Distribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    Distribution selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    List<Distribution> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Distribution record);
}