package test.dao;

import java.util.List;
import test.model.Orderfrom;

public interface OrderfromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderfrom
     *
     * @mbg.generated
     */
    int insert(Orderfrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderfrom
     *
     * @mbg.generated
     */
    List<Orderfrom> selectAll();
}