package test.dao;

import java.util.List;
import test.model.Receipt;

public interface ReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated
     */
    int insert(Receipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated
     */
    List<Receipt> selectAll();
}